### PR TITLE
support to parse and dump symtab command

### PR DESCRIPTION
**Pull request by flier**
solve #2 requests

### CODE REVIEW

**Comment by conradev** [comment]
This looks great to me!

At some point the `desc` field should probably be parsed into a struct (either that, or methods like `is_weak()` should be added to `Symbol`), but definitely not needed for the first pass on symbol stuff.

**Comment by conradev** [comment]
Actually a `fn name(&self) -> Option<&str>` method would be fantastic on `Symbol`

**Comment by flier** [comment]
sure, I have added a Reference trait for `desc`

**Comment by conradev** [comment]
This looks great. Thanks for all of the hard work!

I see that you incremented the version in one of these changes. It might be worth tagging in the repo by version and perhaps even uploading to `crates.io`! The existing packages there are fairly incomplete compared to this one.

**Comment by flier** [comment]
sure, I have upload a release to crates.io, the package has to be renamed to `mach_object`

https://github.com/flier/rust-macho/releases/tag/0.1.1

**Comment by conradev** [comment]
Awesome!

You could have left the `lib` name as `macho` and changed the `package` name to `rust_macho` to avoid conflicts, but renaming both to `mach_object` is another good solution! 🎆

**Pull request merged**
